### PR TITLE
fix: Clean Coinbase Wallet QR Scans

### PR DESCRIPTION
**Pull request by ChangoMan**
## Description

While fixing the scan issue for the send drawer, I noticed that scanning my coinbase wallet QR code wasn't working. It seems like they are appending `ethereum:` to the address.

This PR will strip that out so that coinbase wallet QR codes will work when scanned.

### CODE REVIEW

**Review by carletex — COMMENTED** [review]
Oh, I remember this from when we did the Testnet Dropper in Denver last year.

https://github.com/carletex/testnet-dropper/blob/main/packages/nextjs/pages/index.tsx#L143

I don't remember why we had the @ split too, but I guess some wallets add an extra thing? Do you remember @damianmarti ?

**Comment by damianmarti** [comment]
> Oh, I remember this from when we did the Testnet Dropper in Denver last year.
> 
> https://github.com/carletex/testnet-dropper/blob/main/packages/nextjs/pages/index.tsx#L143
> 
> I don't remember why we had the @ split too, but I guess some wallets add an extra thing? Do you remember @damianmarti ?

Oh, I don't remember why we added this split by @ :-(

**Comment by damianmarti** [comment]
I found the EIP67 standard to use by the format of scanning a QR code, adding the value, gas, and data, maybe we can start implementing the value.

It doesn't mention anything about something with @, so I think we can leave without this split by @.

**Comment by damianmarti** [comment]
@ChangoMan according to EIP67 (https://eips.ethereum.org/EIPS/eip-67) maybe we can split by "?" and we can create an issue to add the value, gas, and data parameters later.

**Comment by ChangoMan** [comment]
> @ChangoMan according to EIP67 (https://eips.ethereum.org/EIPS/eip-67) maybe we can split by "?" and we can create an issue to add the value, gas, and data parameters later.

Ok sounds good, got that added!

**Review by damianmarti — APPROVED** [review]

**Comment by damianmarti** [comment]
> > @ChangoMan according to EIP67 (https://eips.ethereum.org/EIPS/eip-67) maybe we can split by "?" and we can create an issue to add the value, gas, and data parameters later.
> 
> Ok sounds good, got that added!

Thanks!! Merged!

**Pull request merged**
