### PR TITLE
feat: Add Intro Modal

### PR DESCRIPTION
**Pull request by ChangoMan**
## Description

The modal version of https://github.com/BuidlGuidl/burnerwallet/pull/57. I haven't added any spinners yet after clicking the button, still thinking about that part.

Screenshot 2024-06-01 at 11 57 45 AM

Screenshot 2024-06-01 at 11 55 47 AM

### CODE REVIEW

**Comment by carletex** [comment]
Thanks for this @ChangoMan !!

I definitely prefer this approach!! (with some tweaks**) Yes, the landing page can hold more info, but this feels more natural (the transition of closing the modal doesn't feel the same as navigating to another page). If we want to display more info, we can always link to a page with some docs. (from the modal or the settings drawer). **Intuitive experience > a lot of info displayed.**

We didn't have any "welcoming experience" before, so I feel this is a good first iteration. Going for a full landing page feels like too big of a jump.

**Tweaks that I'd make:
- Less text. I can't see the button in my phone. We can probably remove the 2nd paragraph & the 3rd bullet point, and shorten the 2nd bullet point a bit.
- Idea for the animation:
  - When clicking the button, we show a spinner in the button. 
  - At the same time we remove the saturate-0 (or make it less strong)
  - At the same time, we do some randomness magic where the background of the wallet shows diff colors (I guess like creating diff random values). The modal is still open, but you will be able to see it.
  - We do this for 2 seconds? And then close the modal. 

---

In any case, If I'm the only one who likes this option, happy to go with #58 haha. If we are divided we can ask Austin and some other people.

**Comment by ChangoMan** [comment]
Sound like we like the modal! I'll trim down the text, let me know if it looks better on your phone. I'll also mess with the animation and I can add the landing page at `/info` easily.

Should we wait until the wallet connect PR gets merged? This PR will alter the structure quite a bit and might mess up that PR.

**Comment by damianmarti** [comment]
> Sound like we like the modal! I'll trim down the text, let me know if it looks better on your phone. I'll also mess with the animation and I can add the landing page at `/info` easily.
> 
> Should we wait until the wallet connect PR gets merged? This PR will alter the structure quite a bit and might mess up that PR.

Maybe if @Pabl0cks think the WC is working well enough to be merged, we can merge it, and add the known issues as new issues to fix them (I'm working on fixing these issues, but these are not easy ones :-( )

**Comment by Pabl0cks** [comment]
Nice job @ChangoMan!! I really like the modal, the slim version of it looks nice on my mobile and is pretty concise, I like it.

When we merge the extra warning when the user receives real funds, we'll have a double message about doing a pk backup, which I think is good. And there we can be more explicit on the risk on not doing the backup (losing funds).

> What if we move the landing page to another URL, like /info, for now?
> 
> I think that like Pablo commented on the Landing Page PR, this will be useful for people with no context about the Burner Wallet and it will be good content to be indexed by the search engines, so the users can find the site when looking for a wallet.

Now I'm totally up for this modal too! ♥ But yeah we could have a /info or /how-works page explaining all that info. 

Probably won't be enough to get any SEO traffic, unless we start getting nice backlinks to it, but it won't hurt to have it, and can help some users that want to know how their burner works.

**Comment by Pabl0cks** [comment]
> Should we wait until the wallet connect PR gets merged? This PR will alter the structure quite a bit and might mess up that PR.

Tonight I can do the last tests and we merge it? We'll have to continue working and testing on it, and next iteration of WC we can improve the UI/UX a bit too, but since is a bit hidden feature I guess we could merge the first iteration as it is 🙏

**Comment by carletex** [comment]
This is looking great! Now it fits nicely on my phone.

- Yes, we can create a docs / FAQ / info page and link to it from the settings drawer or even the initial modal
- A 1 - 2 seconds animation will be amazing too

But we can tackle these two in different PRs. This looks good for a merge!

Regarding merging #46 , up to Pablo and Damu. Per Pablo's last comment it seems that it's ready! IMO If it's hidden, doesn't need to be super polished. 

Thanks all!

**Comment by damianmarti** [comment]
@ChangoMan #46 is merged now. There are some conflicts to be resolved now. After resolving I can do a final review.

**Comment by ChangoMan** [comment]
@damianmarti Merge conflicts should be resolved!

**Review by damianmarti — APPROVED** [review]
Looks great!! Thanks!

**Pull request merged**
