### PR TITLE
feat: Import Private Key

### PR DESCRIPTION
**Pull request by ChangoMan**
## Description

Allows a user to import a Private Key, replacing their current burner wallet

### CODE REVIEW

**Review by Pabl0cks — APPROVED** [review]
TY for tackling this @ChangoMan! 

Tried it and is working nice, just a couple of issues with the settings drawer:
- When using the "Import private key" on mobile, the keyboard is pushing up the drawer background.
- When you have open both "Copy Private Key" and "Import Private Key" sections, in medium to small screens it does not fit, and there is no way to scroll.

<details>
<summary> Picture of both issues </summary>

Sorry for this picture! Could not screenshot from mobile!
image

This one happens also in my laptop, not only mobile:
image
</details>

Will create a different issue to tweak a bit Settings drawer UI, if you prefer I can move these to the new issue.

**Comment by ChangoMan** [comment]
@Pabl0cks thanks for testing this! I've changed the accordion so that only one can be open at a time, and also tightened up the spacing. It still might be a bit cramped, but hopefully it's better.

**Comment by Pabl0cks** [comment]
TYSM @ChangoMan! Looking great to me now.

Also saw you implemented #45 🙌

**Review by damianmarti — APPROVED** [review]
Thanks @ChangoMan !!! 

I left only a small comment.

**Pull request merged**
